Repository QGEP/docs, pull requests merged in 2022-02, with the labels that each got.

#176 Fix some of the sphinx errors to ease log reading
  .gitignore
  en/admin-guide/db-update-pum/index.rst
  en/admin-guide/interlis-io/index.rst
  en/admin-guide/security/index.rst
  en/installation-guide/database-initialization.rst
  en/installation-guide/workstation.rst
  en/qgep_swmm/Import-Results.rst
  en/user-guide/How-To/index.rst
  en/user-guide/digitizing/dataentry.rst
  en/user-guide/digitizing/deletingobjects.rst
  en/user-guide/digitizing/digitizingwastewaterstructures.rst
  en/user-guide/editing/connect_wastewater_network_elements.rst
  en/user-guide/editing/editing.rst
  en/user-guide/editing/moving.rst
  en/user-guide/layerexplanations/index.rst
  en/user-guide/layerexplanations/namingconventions.rst
  en/user-guide/network-following/index.rst
  en/wincan2qgep/fixing-issues.rst
Labels: bug, documentation

#177 Portable shebang
  scripts/build-docs.sh
Labels: enhancement

#174 Update server.rst
  en/installation-guide/database-initialization.rst
  en/installation-guide/images/macEnvVarCheck.png
  en/installation-guide/images/macEnvVarSet.png
  en/installation-guide/server.rst
  en/installation-guide/workstation.rst
  macEnvVarCheck.png
  macEnvVarSet.png
Labels: enhancement, documentation
